# Generated by Django 3.1 on 2020-08-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruduser',
            name='gender',
        ),
    ]
