# Generated by Django 3.0.5 on 2020-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_cruduser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
